version: '3.8'

services:
  uwsgi:
    build:
      context: ..
    env_file:
      - env_file/env.mysql
      - env_file/env.app
    volumes:
      - ..:/var/www
    command: ["uwsgi", "--ini", "/var/www/uwsgi.ini"]
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3031/health"]
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:1.19.6-alpine
    volumes:
      - /tmp/nginx_log:/var/log/nginx
      - ../nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - uwsgi
    ports:
      - "5000:80"

  mysql:
    image: mysql:8.3.0
    volumes:
      - ./mysql/schema/user.sql:/docker-entrypoint-initdb.d/01_schema_user.sql
      - ./mysql/data/user.sql:/docker-entrypoint-initdb.d/11_data_user.sql
      - ./mysql/conf.d/:/etc/mysql/conf.d/
    env_file:
      - env_file/env.mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
