name: test
on:
  pull_request:
    paths:
      - 'sample/**'
      - 'tests/**'
      - .github/workflows/test.yml
  push:
    branches:
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start mysql
        run: |
          docker-compose -f docker/docker-compose.yml up -d mysql

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Pytest
        timeout-minutes: 1
        run: |
          make init test

      - name: Codecov
        uses: codecov/codecov-action@v3
