name: test
on:
  pull_request:
    paths:
      - 'src/sample/**'

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          submodules: true

      - name: Start mysql
        run: |
          docker-compose -f docker/docker-compose.yml up -d mysql

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Pytest
        timeout-minutes: 1
        working-directory: src
        run: |
          pip install -r sample/requirements.txt -r tests/requirements.txt
          python -m pytest
