name: test
on:
  pull_request:
    paths:
      - 'sample/**'
      - .github/workflows/test.yml
  push:
    branches:
      - master
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Poetry
        uses: ./.github/actions/setup-poetry

      - name: Export requirements.txt
        run: |
          poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Check if requirements.txt is up to date
        run: |
          git diff --exit-code --quiet requirements.txt

      - name: Start mysql
        run: |
          docker-compose -f docker/docker-compose.yml up -d mysql --wait

      - name: Pytest
        timeout-minutes: 1
        run: |
          make init test

      - name: Codecov
        uses: codecov/codecov-action@v3
